AppReciclatonV1/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :alliances
  resources :supplies
  resources :demands
  resources :residues
  resources :categories

  root to: "home#indexreciclaton"

  post '/send', to: 'home#enviar_correo', as: :send_email

  
  get '/compra_venta', to: 'home#compra_venta', as: :compra_venta
  get '/l_reciclaje', to: 'home#l_reciclaje', as: :l_reciclaje
  get '/red_reciclatones', to: 'home#red_reciclatones', as: :red_reciclatones
  get '/nosotros', to: 'home#nosotros', as: :nosotros
  get '/contactenos', to: 'home#contactenos', as: :contactenos
  get '/camp_sens', to: 'home#camp_sens', as: :camp_sens

  devise_for :clients, controllers: {sessions: 'sessions', registrations: 'registrations', :omniauth_callbacks => "clients/omniauth_callbacks"} 

  resources :clients

end

AppReciclatonV1/app/models/residue.rb
class Residue < ActiveRecord::Base

belongs_to :demand
belongs_to :supply
belongs_to :category

end

AppReciclatonV1/app/controllers/residues_controller.rb
class ResiduesController < ApplicationController
  before_action :set_residue, only: [:show, :edit, :update, :destroy]

  # GET /residues
  # GET /residues.json
  def index
    @residues = Residue.all
  end

  # GET /residues/1
  # GET /residues/1.json
  def show
  end

  # GET /residues/new
  def new
    @residue = Residue.new
  end

  # GET /residues/1/edit
  def edit
  end

  # POST /residues
  # POST /residues.json
  def create
    @residue = Residue.new(residue_params)

    respond_to do |format|
      if @residue.save
        format.html { redirect_to @residue, notice: 'Residue was successfully created.' }
        format.json { render :show, status: :created, location: @residue }
      else
        format.html { render :new }
        format.json { render json: @residue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residues/1
  # PATCH/PUT /residues/1.json
  def update
    respond_to do |format|
      if @residue.update(residue_params)
        format.html { redirect_to @residue, notice: 'Residue was successfully updated.' }
        format.json { render :show, status: :ok, location: @residue }
      else
        format.html { render :edit }
        format.json { render json: @residue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residues/1
  # DELETE /residues/1.json
  def destroy
    @residue.destroy
    respond_to do |format|
      format.html { redirect_to residues_url, notice: 'Residue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_residue
      @residue = Residue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def residue_params
      params.require(:residue).permit(:name_redidue, :category_id, :available_quantity)
    end
end

AppReciclatonV1/app/helpers/residues_helper.rb
module ResiduesHelper
end

AppReciclatonV1/app/views/residues/_form.html.erb
<%= form_for(@residue) do |f| %>
  <% if @residue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@residue.errors.count, "error") %> prohibited this residue from being saved:</h2>

      <ul>
      <% @residue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_redidue %><br>
    <%= f.text_field :name_redidue %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :available_quantity %><br>
    <%= f.text_field :available_quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

AppReciclatonV1/app/views/residues/edit.html.erb
<h1>Editing Residue</h1>

<%= render 'form' %>

<%= link_to 'Show', @residue %> |
<%= link_to 'Back', residues_path %>

AppReciclatonV1/app/views/residues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Residues</h1>

<table>
  <thead>
    <tr>
      <th>Name redidue</th>
      <th>Category</th>
      <th>Available quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @residues.each do |residue| %>
      <tr>
        <td><%= residue.name_redidue %></td>
        <td><%= residue.category_id %></td>
        <td><%= residue.available_quantity %></td>
        <td><%= link_to 'Show', residue %></td>
        <td><%= link_to 'Edit', edit_residue_path(residue) %></td>
        <td><%= link_to 'Destroy', residue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Residue', new_residue_path %>

AppReciclatonV1/app/views/residues/new.html.erb
<h1>New Residue</h1>

<%= render 'form' %>

<%= link_to 'Back', residues_path %>

AppReciclatonV1/app/views/residues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name redidue:</strong>
  <%= @residue.name_redidue %>
</p>

<p>
  <strong>Category:</strong>
  <%= @residue.category_id %>
</p>

<p>
  <strong>Available quantity:</strong>
  <%= @residue.available_quantity %>
</p>

<%= link_to 'Edit', edit_residue_path(@residue) %> |
<%= link_to 'Back', residues_path %>