AppReciclatonV1/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :alliances
  resources :supplies
  resources :demands
  resources :residues
  resources :categories

  root to: "home#indexreciclaton"

  post '/send', to: 'home#enviar_correo', as: :send_email

  
  get '/compra_venta', to: 'home#compra_venta', as: :compra_venta
  get '/l_reciclaje', to: 'home#l_reciclaje', as: :l_reciclaje
  get '/red_reciclatones', to: 'home#red_reciclatones', as: :red_reciclatones
  get '/nosotros', to: 'home#nosotros', as: :nosotros
  get '/contactenos', to: 'home#contactenos', as: :contactenos
  get '/camp_sens', to: 'home#camp_sens', as: :camp_sens

  devise_for :clients, controllers: {sessions: 'sessions', registrations: 'registrations', :omniauth_callbacks => "clients/omniauth_callbacks"} 

  resources :clients

end

AppReciclatonV1/app/models/demand.rb
class Demand < ActiveRecord::Base

	belongs_to :client
	has_one :residue
	has_many :alliances
end

AppReciclatonV1/app/controllers/demands_controller.rb
class DemandsController < ApplicationController
  before_action :set_demand, only: [:show, :edit, :update, :destroy]

  # GET /demands
  # GET /demands.json
  def index
    @demands = Demand.all
  end

  # GET /demands/1
  # GET /demands/1.json
  def show
  end

  # GET /demands/new
  def new
    @demand = Demand.new
  end

  # GET /demands/1/edit
  def edit
  end

  # POST /demands
  # POST /demands.json
  def create
    @demand = Demand.new(demand_params)

    respond_to do |format|
      if @demand.save
        format.html { redirect_to @demand, notice: 'Demanda creada con exito' }
        format.json { render :show, status: :created, location: @demand }
      else
        format.html { render :new }
        format.json { render json: @demand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demands/1
  # PATCH/PUT /demands/1.json
  def update
    respond_to do |format|
      if @demand.update(demand_params)
        format.html { redirect_to @demand, notice: 'Demand was successfully updated.' }
        format.json { render :show, status: :ok, location: @demand }
      else
        format.html { render :edit }
        format.json { render json: @demand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demands/1
  # DELETE /demands/1.json
  def destroy
    @demand.destroy
    respond_to do |format|
      format.html { redirect_to demands_url, notice: 'Demand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demand
      @demand = Demand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demand_params
      params.require(:demand).permit(:client_id, :residue_id, :demanded_monthly_quantity, :state)
    end
end

AppReciclatonV1/app/helpers/demands_helper.rb
module DemandsHelper
end

AppReciclatonV1/app/views/demands/_form.html.erb
<%= form_for(@demand) do |f| %>
  <% if @demand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@demand.errors.count, "error") %> prohibited this demand from being saved:</h2>

      <ul>
      <% @demand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.text_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :residue_id %><br>
    <%= f.text_field :residue_id %>
  </div>
  <div class="field">
    <%= f.label :demanded_monthly_quantity %><br>
    <%= f.text_field :demanded_monthly_quantity %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.number_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

AppReciclatonV1/app/views/demands/edit.html.erb
<h1>Editar demanda</h1>

<%= render 'form' %>

<%= link_to 'Show', @demand %> |
<%= link_to 'Back', demands_path %>

AppReciclatonV1/app/views/demands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Demands</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Residue</th>
      <th>Demanded monthly quantity</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @demands.each do |demand| %>
      <tr>
        <td><%= demand.client_id %></td>
        <td><%= demand.residue_id %></td>
        <td><%= demand.demanded_monthly_quantity %></td>
        <td><%= demand.state %></td>
        <td><%= link_to 'Show', demand %></td>
        <td><%= link_to 'Edit', edit_demand_path(demand) %></td>
        <td><%= link_to 'Destroy', demand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Demand', new_demand_path %>

AppReciclatonV1/app/views/demands/new.html.erb
<div class= "row">
  <div class="col-md-4 col-md-offset-4">
		<h1>Nueva Demanda</h1>

		<%= render 'form' %>

		<%= link_to 'Back', compra_venta_path %>

</div>
</div>

AppReciclatonV1/app/views/demands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @demand.client_id %>
</p>

<p>
  <strong>Residue:</strong>
  <%= @demand.residue_id %>
</p>

<p>
  <strong>Demanded monthly quantity:</strong>
  <%= @demand.demanded_monthly_quantity %>
</p>

<p>
  <strong>State:</strong>
  <%= @demand.state %>
</p>

<%= link_to 'Edit', edit_demand_path(@demand) %> |
<%= link_to 'Back', demands_path %>