AppReciclatonV1/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :alliances
  resources :supplies
  resources :demands
  resources :residues
  resources :categories

  root to: "home#indexreciclaton"

  post '/send', to: 'home#enviar_correo', as: :send_email

  
  get '/compra_venta', to: 'home#compra_venta', as: :compra_venta
  get '/l_reciclaje', to: 'home#l_reciclaje', as: :l_reciclaje
  get '/red_reciclatones', to: 'home#red_reciclatones', as: :red_reciclatones
  get '/nosotros', to: 'home#nosotros', as: :nosotros
  get '/contactenos', to: 'home#contactenos', as: :contactenos
  get '/camp_sens', to: 'home#camp_sens', as: :camp_sens

  devise_for :clients, controllers: {sessions: 'sessions', registrations: 'registrations', :omniauth_callbacks => "clients/omniauth_callbacks"} 

  resources :clients

end

AppReciclatonV1/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

AppReciclatonV1/app/models/alliance.rb
class Alliance < ActiveRecord::Base

	belongs_to :client_supplier, class_name: 'Client', foreign_key: 'client_supplier_id'
	belongs_to :client_recipient, class_name: 'Client', foreign_key: 'client_recipient_id'
	belongs_to :supply
	belongs_to :demand
end

AppReciclatonV1/app/models/category.rb
class Category < ActiveRecord::Base

	has_many :residues
	
end

AppReciclatonV1/app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :demand
	has_many :supply
	has_many :alliances_supply, class_name: 'Alliance', foreign_key: "client_supplier_id"
	has_many :alliances_recipient, class_name: 'Alliance', foreign_key: "client_recipient_id"


	mount_uploader :avatar, ProfilePhotoUploader

	devise :omniauthable, :omniauth_providers => [:facebook]

	def self.from_omniauth(auth)
	    where(provider: auth.provider, uid: auth.uid).first_or_create do |client|
	      client.email = auth.info.email
	      client.password = Devise.friendly_token[0,20]
	      client.name_complet = auth.info.name   # assuming the user model has a name
	      client.avatar = auth.info.image # assuming the user model has an image
    	end
	end

	def self.new_with_session(params, session)
    super.tap do |client|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        client.email = data["email"] if client.email.blank?
      end
    end
  end

end

AppReciclatonV1/app/models/demand.rb
class Demand < ActiveRecord::Base

	belongs_to :client
	has_one :residue
	has_many :alliances
end

AppReciclatonV1/app/models/residue.rb
class Residue < ActiveRecord::Base

belongs_to :demand
belongs_to :supply
belongs_to :category

end

AppReciclatonV1/app/models/supply.rb
class Supply < ActiveRecord::Base

	belongs_to :client
	has_one :residue
	has_many :alliances
end

AppReciclatonV1/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name_complet, :customer_type, :identification_number, :ubication, :profile_photo)
    end
end

AppReciclatonV1/app/controllers/demands_controller.rb
class DemandsController < ApplicationController
  before_action :set_demand, only: [:show, :edit, :update, :destroy]

  # GET /demands
  # GET /demands.json
  def index
    @demands = Demand.all
  end

  # GET /demands/1
  # GET /demands/1.json
  def show
  end

  # GET /demands/new
  def new
    @demand = Demand.new
  end

  # GET /demands/1/edit
  def edit
  end

  # POST /demands
  # POST /demands.json
  def create
    @demand = Demand.new(demand_params)

    respond_to do |format|
      if @demand.save
        format.html { redirect_to @demand, notice: 'Demanda creada con exito' }
        format.json { render :show, status: :created, location: @demand }
      else
        format.html { render :new }
        format.json { render json: @demand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demands/1
  # PATCH/PUT /demands/1.json
  def update
    respond_to do |format|
      if @demand.update(demand_params)
        format.html { redirect_to @demand, notice: 'Demand was successfully updated.' }
        format.json { render :show, status: :ok, location: @demand }
      else
        format.html { render :edit }
        format.json { render json: @demand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demands/1
  # DELETE /demands/1.json
  def destroy
    @demand.destroy
    respond_to do |format|
      format.html { redirect_to demands_url, notice: 'Demand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demand
      @demand = Demand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demand_params
      params.require(:demand).permit(:client_id, :residue_id, :demanded_monthly_quantity, :state)
    end
end

AppReciclatonV1/app/controllers/home_controller.rb
class HomeController < ApplicationController


def index
end

def compra_venta
	@supplies = Supply.all
	@demands = Demand.all
end

def l_reciclaje
	@categories = Category.all
end

def red_reciclatones
end

def nosotros
end

def contactenos
end

def camp_sens
end

def operacion

end

def enviar_correo

@asunto = params[:asunto]
@contenido = params[:contenido]

ContactMailer.contactame(@asunto,@contenido).deliver_now
redirect_to root_path
end


end

AppReciclatonV1/app/helpers/alliances_helper.rb
module AlliancesHelper
end

AppReciclatonV1/app/helpers/application_helper.rb
module ApplicationHelper
end

AppReciclatonV1/app/helpers/categories_helper.rb
module CategoriesHelper
end

AppReciclatonV1/app/helpers/clients_helper.rb
module ClientsHelper
end

AppReciclatonV1/app/helpers/demands_helper.rb
module DemandsHelper
end

AppReciclatonV1/app/helpers/home_helper.rb
module HomeHelper
end

AppReciclatonV1/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

AppReciclatonV1/app/helpers/residues_helper.rb
module ResiduesHelper
end

AppReciclatonV1/app/helpers/sessions_helper.rb
module SessionsHelper
end

AppReciclatonV1/app/helpers/supplies_helper.rb
module SuppliesHelper
end

AppReciclatonV1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppReciclaton</title>
  

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="favicon.ico">
  
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />
  <link href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.1/animate.min.css" rel="stylesheet" />

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      
    <![endif]-->


  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

  <!-- Libreria Estadisticas -->
  <script src="https://d3js.org/d3.v3.min.js" charset="utf-8"></script>
  <!--Fin estadisticas reciclaje -->

  

<!--[if lt IE 9]>
    <script src="js/respond-1.1.0.min.js"></script>
    <script src="js/html5shiv.js"></script>
    <script src="js/html5element.js"></script>
<![endif]-->



  <link href='https://fonts.googleapis.com/css?family=Gloria+Hallelujah' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Chewy' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Fjalla+One' rel='stylesheet' type='text/css'>

  <title>Reciclatón</title>
   
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <%= csrf_meta_tags %>
</head>



<body>
  <!-- Fixed navbar -->
  <div class= "row">
    <nav class="navbar navbar-default navbar-fixed-top application">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
              </button>
      <a class="navbar-brand" class="active" href="<%= root_path %>"><span class="sr-only">(current)</span><img src="<%=image_path('reciclatonlogo.png')%>" style="width:30px;height:28px;position:center;">Reciclatón</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
              
                  <li><a href="<%= compra_venta_path %>">Compra/Venta Residuos</a></li>
                  <li><a href="<%= l_reciclaje_path %>">Líneas de reciclaje</a></li>
                  <li><a href="<%= red_reciclatones_path %>">Red de reciclatones</a></li>
                  <li><a href="<%= nosotros_path %>">Nosotros</a></li>
                  <li><a href="<%= contactenos_path %>">Contáctenos</a></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Campaña de sensibilizacion<span class="caret"></span></a>
              <ul class="dropdown-menu">
                    <li><a href="#">Tips de reciclaje</a></li>
                    <li><a href="#">Clases presenciales</a></li>
                    <li><a href="#">Clases virtuales</a></li>
                    <li><a href="#">Tutoriales</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Otros</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Puntos de reciclaje inteligente</a></li>
              </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Buscar en la página">
          </div>
          <button type="submit" class="btn btn-default">Buscar!</button>
      </form>

                <ul class="nav navbar-nav navbar-right">
        
                  <% if client_signed_in? %>
                    <li>
                      <p>Bienvenid@ <%= current_client.name_complet%></p>
                    <%= link_to('Cerrar sesión', destroy_client_session_path, :method => :delete) %>    
                    </li>
                  <% else %>
                    
                    <li class="navlogin">
                    <a href="#" data-toggle="modal" data-target="#myModal">Iniciar sesión</a>
                    </li>
                  
              
                    <li class="navlogin">
                    <%= link_to('Soy nuevo usuario', new_client_registration_path)%>
                    </li>
              
                  <% end %>
                </ul>

                  <div class="dropdown navbar-right">
                        <button class="btn btn-default dropdown-toggle navbar-btn" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Lenguaje
                            <span class="caret"></span>
                        </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                      <li><a href="<%= root_path(locale: 'en') %>">Inglés</a></li>
                      <li><a href="<%= root_path(locale: 'es') %>">Español</a></li>
                    </ul>
                  </div>


        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

       
</nav>
  

<%= render partial: 'partials/loginmodal' %>




 <%= yield %>   

</body>
</html>





<div id="cboxbutton" style="position: fixed; bottom: 8px; right: 16px; padding: 3px 20px; text-align: center; cursor: pointer; background-color: #EDF3F7; border:#C3D7E5 1px solid;border-radius: 3px; font-family: Tahoma, sans-serif; font-size: 14px; font-weight: bold"></div>
<div id="cboxwrap" style="position: fixed; bottom: 48px; right: 16px; background: #3CB371; padding: 3px; border:#C3D7E5 1px solid;border-radius: 3px;"></div>

<script>
/*
* Cbox dynamic loader v.2
*/
(function () {
  var showByDefault = true;
  var cboxContainer = document.getElementById("cboxwrap");
  var cboxToggleButton = document.getElementById("cboxbutton");
  var buttonStringOpen = "Open Cbox";
  var buttonStringClose = "Close Cbox";
  var lsKey = "cbox:isOpen";

  var cboxHTML = '<!-- BEGIN CBOX - www.cbox.ws - v4.3 -->'
  +'<div id="cboxdiv" style="position: relative; margin: 0 auto; width: 200px; font-size: 0; line-height: 0;">'
  +'<div style="position: relative; height: 300px; overflow: auto; overflow-y: auto; -webkit-overflow-scrolling: touch; border: 0px solid;"><iframe src="http://www3.cbox.ws/box/?boxid=3494336&boxtag=xwcqa9&sec=main" marginheight="0" marginwidth="0" frameborder="0" width="100%" height="100%" scrolling="auto" allowtransparency="yes" name="cboxmain3-3494336" id="cboxmain3-3494336"></iframe></div>'
  +'<div style="position: relative; height: 80px; overflow: hidden; border: 0px solid; border-top: 0px;"><iframe src="http://www3.cbox.ws/box/?boxid=3494336&boxtag=xwcqa9&sec=form" marginheight="0" marginwidth="0" frameborder="0" width="100%" height="100%" scrolling="no" allowtransparency="yes" name="cboxform3-3494336" id="cboxform3-3494336"></iframe></div>'
  +'</div>'
  +'<!-- END CBOX -->';

  var htmlInjected = false;
  var isVisible = false;
  var toggleCbox = function (show) {
    
    if (!show) {
      cboxContainer.style.display = "none";
      if (cboxToggleButton) {
        cboxToggleButton.innerHTML = buttonStringOpen;
      }
      
    }
    else {
      cboxContainer.style.display = "block";
      if (cboxToggleButton) {
        cboxToggleButton.innerHTML = buttonStringClose;
      }
    }
    
    if (show && !htmlInjected) {
      cboxContainer.innerHTML = cboxHTML;
      htmlInjected = true;
    }
    
    isVisible = show;
  }

  if (localStorage && lsKey && typeof localStorage.getItem(lsKey) === "string") {
    toggleCbox((localStorage.getItem(lsKey) === "yes"));
  }
  else {
    toggleCbox(showByDefault);
  }

  if (cboxToggleButton) {
    cboxToggleButton.onclick = function () {
      toggleCbox(!isVisible);
      
      if (localStorage && lsKey) {
        localStorage.setItem(lsKey, isVisible ? "yes" : "no");
      }
    }
  }
})();

</script> 

AppReciclatonV1/app/views/partials/_login_form.html.erb
<%= form_for(Client.new, as: :client, url: client_session_path) do |f| %>
  <div class="alert alert-danger errors" style="display: none"></div>

<div >

  <div class= "row">
      <div class="col-md-10 col-md-offset-2">

        <div class="form-group" placeholder="Ingrese correo electrónico">
          <%= f.label :email, "Correo electrónico" %><br />
          <%= f.email_field :email, autofocus: true, class: 'form-control' %>
        </div>

        <div class="form-group" placeholder="Ingrese contraseña">
          <%= f.label :password, "Contraseña" %><br />
          <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
        </div>


        <div class="form-group">
          <%= f.submit "Iniciar", class: "btn btn-success btn-lg" %>
        </div>


        <p><%= link_to "Iniciar sesión con Facebook", client_omniauth_authorize_path(:facebook)%></p> 

        <p><%= link_to "Registrarme", new_client_registration_path %></p>

  </div>
    </div>

</div>

<% end %>

AppReciclatonV1/app/views/partials/_loginmodal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content login">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Inicio de sesión</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'partials/login_form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

AppReciclatonV1/app/views/partials/_register_form.html.erb
<%= form_for(Client.new, as: :client, url: registration_path(:client), html: { class: "registration-form" }) do |f| %>
  <div class="alert alert-danger errors" style="display: none"></div>
  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up", class: "btn btn-success btn-lg" %>
  </div>
<% end %>


<%= render partial: 'partials/register_form' %>

AppReciclatonV1/app/views/partials/_register_modal.html.erb
<div class="modal fade" id="register-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Register</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'partials/register_form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>