AppReciclatonV1/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :alliances
  resources :supplies
  resources :demands
  resources :residues
  resources :categories

  root to: "home#indexreciclaton"

  post '/send', to: 'home#enviar_correo', as: :send_email

  
  get '/compra_venta', to: 'home#compra_venta', as: :compra_venta
  get '/l_reciclaje', to: 'home#l_reciclaje', as: :l_reciclaje
  get '/red_reciclatones', to: 'home#red_reciclatones', as: :red_reciclatones
  get '/nosotros', to: 'home#nosotros', as: :nosotros
  get '/contactenos', to: 'home#contactenos', as: :contactenos
  get '/camp_sens', to: 'home#camp_sens', as: :camp_sens

  devise_for :clients, controllers: {sessions: 'sessions', registrations: 'registrations', :omniauth_callbacks => "clients/omniauth_callbacks"} 

  resources :clients

end

AppReciclatonV1/app/models/supply.rb
class Supply < ActiveRecord::Base

	belongs_to :client
	has_one :residue
	has_many :alliances
end

AppReciclatonV1/app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  before_action :set_supply, only: [:show, :edit, :update, :destroy]

  # GET /supplies
  # GET /supplies.json
  def index
    @supplies = Supply.all
  end

  # GET /supplies/1
  # GET /supplies/1.json
  def show
  end

  # GET /supplies/new
  def new
    @supply = Supply.new
  end

  # GET /supplies/1/edit
  def edit
  end

  # POST /supplies
  # POST /supplies.json
  def create
    @supply = Supply.new(supply_params)

    respond_to do |format|
      if @supply.save
        format.html { redirect_to @supply, notice: 'Oferta creada con exito' }
        format.json { render :show, status: :created, location: @supply }
      else
        format.html { render :new }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplies/1
  # PATCH/PUT /supplies/1.json
  def update
    respond_to do |format|
      if @supply.update(supply_params)
        format.html { redirect_to @supply, notice: 'Supply was successfully updated.' }
        format.json { render :show, status: :ok, location: @supply }
      else
        format.html { render :edit }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplies/1
  # DELETE /supplies/1.json
  def destroy
    @supply.destroy
    respond_to do |format|
      format.html { redirect_to supplies_url, notice: 'Supply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supply
      @supply = Supply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supply_params
      params.require(:supply).permit(:client_id, :residue_id, :supplied_monthly_quantity, :stock, :state)
    end
end

AppReciclatonV1/app/helpers/supplies_helper.rb
module SuppliesHelper
end

AppReciclatonV1/app/views/supplies/_form.html.erb
<%= form_for(@supply) do |f| %>
  <% if @supply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supply.errors.count, "error") %> prohibited this supply from being saved:</h2>

      <ul>
      <% @supply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.text_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :residue_id %><br>
    <%= f.text_field :residue_id %>
  </div>
  <div class="field">
    <%= f.label :supplied_monthly_quantity %><br>
    <%= f.text_field :supplied_monthly_quantity %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.number_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

AppReciclatonV1/app/views/supplies/edit.html.erb
<h1>Editar oferta</h1>

<%= render 'form' %>

<%= link_to 'Show', @supply %> |
<%= link_to 'Back', supplies_path %>

AppReciclatonV1/app/views/supplies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Supplies</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Residue</th>
      <th>Supplied monthly quantity</th>
      <th>Stock</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @supplies.each do |supply| %>
      <tr>
        <td><%= supply.client_id %></td>
        <td><%= supply.residue_id %></td>
        <td><%= supply.supplied_monthly_quantity %></td>
        <td><%= supply.stock %></td>
        <td><%= supply.state %></td>
        <td><%= link_to 'Show', supply %></td>
        <td><%= link_to 'Edit', edit_supply_path(supply) %></td>
        <td><%= link_to 'Destroy', supply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supply', new_supply_path %>

AppReciclatonV1/app/views/supplies/new.html.erb
<div class= "row">
  <div class="col-md-4 col-md-offset-4">

		<h1>Nueva oferta</h1>

		<%= render 'form' %>

		<%= link_to 'Back', compra_venta_path %>

</div>
</div>

AppReciclatonV1/app/views/supplies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @supply.client_id %>
</p>

<p>
  <strong>Residue:</strong>
  <%= @supply.residue_id %>
</p>

<p>
  <strong>Supplied monthly quantity:</strong>
  <%= @supply.supplied_monthly_quantity %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @supply.stock %>
</p>

<p>
  <strong>State:</strong>
  <%= @supply.state %>
</p>

<%= link_to 'Edit', edit_supply_path(@supply) %> |
<%= link_to 'Back', supplies_path %>